set_property SRC_FILE_INFO {cfile:/home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/constrs_1/imports/constraints/dmaDemo.xdc rfile:../../../Multiple-Core.srcs/constrs_1/imports/constraints/dmaDemo.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports SDATA_I]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SDATA_I]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports BCLK_O]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports BCLK_O]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6 [get_ports SDATA_O]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SDATA_O]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5 [get_ports LRCLK_O]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports LRCLK_O]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports MCLK_O]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports MCLK_O]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G4 [get_ports CPU_RESETN]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M2   } [get_ports { DDR3_ADDR[0] }]; #IO_L16N_T2_35 Sch=ddr3_addr[0]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M5   } [get_ports { DDR3_ADDR[1] }]; #IO_L23N_T3_35 Sch=ddr3_addr[1]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L5   } [get_ports { DDR3_ADDR[10] }]; #IO_L18P_T2_35 Sch=ddr3_addr[10]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N5   } [get_ports { DDR3_ADDR[11] }]; #IO_L24N_T3_35 Sch=ddr3_addr[11]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N4   } [get_ports { DDR3_ADDR[12] }]; #IO_L19P_T3_35 Sch=ddr3_addr[12]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P2   } [get_ports { DDR3_ADDR[13] }]; #IO_L22P_T3_35 Sch=ddr3_addr[13]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P6   } [get_ports { DDR3_ADDR[14] }]; #IO_L24P_T3_35 Sch=ddr3_addr[14]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M3   } [get_ports { DDR3_ADDR[2] }]; #IO_L16P_T2_35 Sch=ddr3_addr[2]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M1   } [get_ports { DDR3_ADDR[3] }]; #IO_L15P_T2_DQS_35 Sch=ddr3_addr[3]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L6   } [get_ports { DDR3_ADDR[4] }]; #IO_25_35 Sch=ddr3_addr[4]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P1   } [get_ports { DDR3_ADDR[5] }]; #IO_L20N_T3_35 Sch=ddr3_addr[5]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N3   } [get_ports { DDR3_ADDR[6] }]; #IO_L19N_T3_VREF_35 Sch=ddr3_addr[6]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N2   } [get_ports { DDR3_ADDR[7] }]; #IO_L22N_T3_35 Sch=ddr3_addr[7]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M6   } [get_ports { DDR3_ADDR[8] }]; #IO_L23P_T3_35 Sch=ddr3_addr[8]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R1   } [get_ports { DDR3_ADDR[9] }]; #IO_L20P_T3_35 Sch=ddr3_addr[9]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L3   } [get_ports { DDR3_BA[0] }]; #IO_L14P_T2_SRCC_35 Sch=ddr3_ba[0]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K6   } [get_ports { DDR3_BA[1] }]; #IO_L17P_T2_35 Sch=ddr3_ba[1]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L4   } [get_ports { DDR3_BA[2] }]; #IO_L18N_T2_35 Sch=ddr3_ba[2]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K3   } [get_ports { DDR3_CAS }]; #IO_L14N_T2_SRCC_35 Sch=ddr3_cas
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J6   } [get_ports { DDR3_CKE[0] }]; #IO_L17N_T2_35 Sch=ddr3_cke[0]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P4    IOSTANDARD LVDS     } [get_ports { DDR3_CLK_N[0] }]; #IO_L21N_T3_DQS_35 Sch=ddr3_clk_n[0]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P5    IOSTANDARD LVDS     } [get_ports { DDR3_CLK_P[0] }]; #IO_L21P_T3_DQS_35 Sch=ddr3_clk_p[0]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G3   } [get_ports { DDR3_DM[0] }]; #IO_L11N_T1_SRCC_35 Sch=ddr3_dm[0]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F1   } [get_ports { DDR3_DM[1] }]; #IO_L5N_T0_AD13N_35 Sch=ddr3_dm[1]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G2   } [get_ports { DDR3_DQ[0] }]; #IO_L8N_T1_AD14N_35 Sch=ddr3_dq[0]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H4   } [get_ports { DDR3_DQ[1] }]; #IO_L12P_T1_MRCC_35 Sch=ddr3_dq[1]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F3   } [get_ports { DDR3_DQ[10] }]; #IO_L6P_T0_35 Sch=ddr3_dq[10]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D2   } [get_ports { DDR3_DQ[11] }]; #IO_L4N_T0_35 Sch=ddr3_dq[11]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C2   } [get_ports { DDR3_DQ[12] }]; #IO_L2P_T0_AD12P_35 Sch=ddr3_dq[12]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A1   } [get_ports { DDR3_DQ[13] }]; #IO_L1N_T0_AD4N_35 Sch=ddr3_dq[13]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E2   } [get_ports { DDR3_DQ[14] }]; #IO_L4P_T0_35 Sch=ddr3_dq[14]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B1   } [get_ports { DDR3_DQ[15] }]; #IO_L1P_T0_AD4P_35 Sch=ddr3_dq[15]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H5   } [get_ports { DDR3_DQ[2] }]; #IO_L10N_T1_AD15N_35 Sch=ddr3_dq[2]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J1   } [get_ports { DDR3_DQ[3] }]; #IO_L7N_T1_AD6N_35 Sch=ddr3_dq[3]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K1   } [get_ports { DDR3_DQ[4] }]; #IO_L7P_T1_AD6P_35 Sch=ddr3_dq[4]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H3   } [get_ports { DDR3_DQ[5] }]; #IO_L11P_T1_SRCC_35 Sch=ddr3_dq[5]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H2   } [get_ports { DDR3_DQ[6] }]; #IO_L8P_T1_AD14P_35 Sch=ddr3_dq[6]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J5   } [get_ports { DDR3_DQ[7] }]; #IO_L10P_T1_AD15P_35 Sch=ddr3_dq[7]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E3   } [get_ports { DDR3_DQ[8] }]; #IO_L6N_T0_VREF_35 Sch=ddr3_dq[8]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B2   } [get_ports { DDR3_DQ[9] }]; #IO_L2N_T0_AD12N_35 Sch=ddr3_dq[9]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J2    IOSTANDARD LVDS     } [get_ports { DDR3_DQS_N[0] }]; #IO_L9N_T1_DQS_AD7N_35 Sch=ddr3_dqs_n[0]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K2    IOSTANDARD LVDS     } [get_ports { DDR3_DQS_P[0] }]; #IO_L9P_T1_DQS_AD7P_35 Sch=ddr3_dqs_p[0]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D1    IOSTANDARD LVDS     } [get_ports { DDR3_DQS_N[1] }]; #IO_L3N_T0_DQS_AD5N_35 Sch=ddr3_dqs_n[1]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E1    IOSTANDARD LVDS     } [get_ports { DDR3_DQS_P[1] }]; #IO_L3P_T0_DQS_AD5P_35 Sch=ddr3_dqs_p[1]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K4   } [get_ports { DDR3_ODT }]; #IO_L13P_T2_MRCC_35 Sch=ddr3_odt
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J4   } [get_ports { DDR3_RAS }]; #IO_L13N_T2_MRCC_35 Sch=ddr3_ras
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G1   } [get_ports { DDR3_RESET }]; #IO_L5P_T0_AD13P_35 Sch=ddr3_reset
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L1   } [get_ports { DDR3_WE }]; #IO_L15N_T2_DQS_35 Sch=ddr3_we
set_property src_info {type:XDC file:1 line:511 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T14 [get_ports {led_tri_o[0]}]
set_property src_info {type:XDC file:1 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T15 [get_ports {led_tri_o[1]}]
set_property src_info {type:XDC file:1 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports {led_tri_o[2]}]
set_property src_info {type:XDC file:1 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {led_tri_o[3]}]
set_property src_info {type:XDC file:1 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V15 [get_ports {led_tri_o[4]}]
set_property src_info {type:XDC file:1 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {led_tri_o[5]}]
set_property src_info {type:XDC file:1 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15 [get_ports {led_tri_o[6]}]
set_property src_info {type:XDC file:1 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y13 [get_ports {led_tri_o[7]}]
set_property src_info {type:XDC file:1 line:621 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports iic_rtl_scl_io]
set_property src_info {type:XDC file:1 line:622 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports iic_rtl_scl_io]
set_property src_info {type:XDC file:1 line:623 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports iic_rtl_sda_io]
set_property src_info {type:XDC file:1 line:624 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports iic_rtl_sda_io]
set_property src_info {type:XDC file:1 line:673 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R4 [get_ports SYSCLK]
