# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.cache/wt [current_project]
set_property parent.project_path /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_repo_paths /home/akayashima/H30_Xilinx/NexysVideoDMA_20181101/repo [current_project]
set_property ip_output_repo /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  {/home/akayashima/Downloads/DDR3 SDRAM Verilog Model/4096Mb_ddr3_parameters.vh}
  {/home/akayashima/Downloads/DDR3 SDRAM Verilog Model/subtest.vh}
}
set_property file_type "Verilog Header" [get_files {{/home/akayashima/Downloads/DDR3 SDRAM Verilog Model/4096Mb_ddr3_parameters.vh}}]
set_property file_type "Verilog Header" [get_files {{/home/akayashima/Downloads/DDR3 SDRAM Verilog Model/subtest.vh}}]
read_mem /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/new/mem_init.txt
read_verilog -library xil_defaultlib -sv {
  {/home/akayashima/Downloads/DDR3 SDRAM Verilog Model/ddr3.v}
  /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/new/ddr3-4096.v
}
read_verilog -library xil_defaultlib {
  /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/imports/hdl/design_1_wrapper.v
  /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/synth/design_1.v
}
add_files /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_mutex_0_0/design_1_mutex_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_1/design_1_mig_7series_0_1/user_design/constraints/design_1_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_1/design_1_mig_7series_0_1/user_design/constraints/design_1_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_1/design_1_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_1/design_1_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_1/design_1_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_1/design_1_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_1/design_1_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_m05_data_fifo_0/design_1_m05_data_fifo_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_s01_data_fifo_0/design_1_s01_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_6/design_1_auto_pc_6_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_s00_data_fifo_0/design_1_s00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_5/design_1_auto_pc_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/constrs_1/imports/constraints/dmaDemo.xdc
set_property used_in_implementation false [get_files /home/akayashima/H31_Xilinx/Img-processing-sim/Multiple-Core.srcs/constrs_1/imports/constraints/dmaDemo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7a200tsbg484-1 -flatten_hierarchy full -directive RuntimeOptimized -fsm_extraction off


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
