webtalk_init -webtalk_dir /home/akayashima/H30_Xilinx/Mutex-20181213/Multiple-Core.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-12-18 16:59:12" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211387882_1777527812_210663870_969" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1sol0246fi8ccdii1g0irg1bjp" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_45" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "45" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.5.1804 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1456.347 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.620 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1545118049000" -context "sdk\\\\hardware/1545118049000"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1545118049000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1545118049000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1545118049000"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.4" -context "sdk\\\\hardware/1545118049000"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1545118049000"
webtalk_add_data -client sdk -key Device -value "7a200t" -context "sdk\\\\hardware/1545118049000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1545118049000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1545118049000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1545118049000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1545118049000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1545119952074"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1545119952074"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1545119952074"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1545119952074"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1545119952074"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1545119952074"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1545119952074"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1545119952074"
webtalk_transmit -clientid 491608099 -regid "211387882_1777527812_210663870_969" -xml /home/akayashima/H30_Xilinx/Mutex-20181213/Multiple-Core.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/akayashima/H30_Xilinx/Mutex-20181213/Multiple-Core.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/akayashima/H30_Xilinx/Mutex-20181213/Multiple-Core.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
